<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Permite compilar para Windows na maquina Linux da fase de nuvem -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>1.0.1</Version>
    <Authors>Manfred Heil Junior</Authors>
    <Company>MT - Manfred Tecnologia</Company>
    <Product>MapHard - MT</Product>
    <Copyright>Copyright (c) 2026 MANFRED TECNOLOGIA LTDA</Copyright>
    <NeutralLanguage>pt-BR</NeutralLanguage>
    <SatelliteResourceLanguages>pt-BR</SatelliteResourceLanguages>
  </PropertyGroup>

  <!-- Na versao de entrega nao sai arquivo .pdb ao lado do .exe -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
